version: '3.8'

services:
  api:
    build: .
    container_name: movie_recommendation_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_PATH=database/database.db
    env_file:
      - .env
