"""add canonical_id and sources to movies

Revision ID: 55e683390c75
Revises: 9913973e36da
Create Date: 2026-04-22 22:49:51.223759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e683390c75'
down_revision: Union[str, Sequence[str], None] = '9913973e36da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_conv_user1_user2', 'conversations', ['user1_id', 'user2_id'], unique=False)
    # Add columns as nullable first
    op.add_column('movies', sa.Column('canonical_id', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('type', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('sources', sa.JSON(), nullable=True))
    
    # Populate existing rows
    op.execute("UPDATE movies SET canonical_id = gen_random_uuid()::text, type = 'movie'")
    
    # Alter columns to be NOT NULL
    op.alter_column('movies', 'canonical_id', nullable=False)
    op.alter_column('movies', 'type', nullable=False)
    op.add_column('movies', sa.Column('sources', sa.JSON(), nullable=True))
    op.alter_column('movies', 'tmdb_id',existing_type=sa.INTEGER(),nullable=True)
    op.alter_column('movies', 'genre_ids',existing_type=sa.VARCHAR(),nullable=True)
    op.drop_constraint(op.f('uq_user_tmdb_movie'), 'movies', type_='unique')
    op.create_index(op.f('ix_movies_canonical_id'), 'movies', ['canonical_id'], unique=False)
    op.create_unique_constraint('uq_user_canonical_movie', 'movies', ['user_id', 'canonical_id'])
    op.drop_column('similarity_matches', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('similarity_matches', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_canonical_movie', 'movies', type_='unique')
    op.drop_index(op.f('ix_movies_canonical_id'), table_name='movies')
    op.create_unique_constraint(op.f('uq_user_tmdb_movie'), 'movies', ['user_id', 'tmdb_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('movies', 'genre_ids',existing_type=sa.VARCHAR(),nullable=False)
    op.alter_column('movies', 'tmdb_id',existing_type=sa.INTEGER(),nullable=False)
    op.drop_column('movies', 'sources')
    op.drop_column('movies', 'type')
    op.drop_column('movies', 'canonical_id')
    op.drop_index('ix_conv_user1_user2', table_name='conversations')
