"""add role column

Revision ID: cb3b12b14df5
Revises:
Create Date: 2026-04-13 20:24:37.501766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb3b12b14df5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if 'role' column already exists to prevent DuplicateColumn error
    conn = op.get_bind()
    inspect_obj = sa.inspect(conn)
    columns = [c["name"] for c in inspect_obj.get_columns("users")]

    if "role" not in columns:
        op.add_column(
            "users",
            sa.Column("role", sa.String(), server_default="user", nullable=False),
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
