"""add constraints and cascade deletes

Revision ID: f1583581fded
Revises: 2fa377f3ceaa
Create Date: 2026-04-18 12:18:33.802543

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1583581fded"
down_revision: Union[str, Sequence[str], None] = "2fa377f3ceaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema with safety checks."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 1. Movies Table: Unique Constraint
    movies_uqs = [c["name"] for c in inspector.get_unique_constraints("movies")]
    if "uq_user_tmdb_movie" not in movies_uqs:
        op.create_unique_constraint(
            "uq_user_tmdb_movie", "movies", ["user_id", "tmdb_id"]
        )

    # 2. Movies Table: Foreign Key with CASCADE
    movies_fks = inspector.get_foreign_keys("movies")
    has_cascade_fk = any(
        fk.get("options", {}).get("ondelete") == "CASCADE" for fk in movies_fks
    )
    if not has_cascade_fk:
        for fk in movies_fks:
            if "user_id" in fk["constrained_columns"]:
                op.drop_constraint(fk["name"], "movies", type_="foreignkey")
        op.create_foreign_key(
            "movies_user_id_fkey_cascade",
            "movies",
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # 3. Watched Movies Table: Unique Constraint
    watched_uqs = [
        c["name"] for c in inspector.get_unique_constraints("watched_movies")
    ]
    if "uq_user_watched_movie" not in watched_uqs:
        op.create_unique_constraint(
            "uq_user_watched_movie", "watched_movies", ["user_id", "movie_id"]
        )

    # 4. Watched Movies Table: Foreign Keys with CASCADE
    watched_fks = inspector.get_foreign_keys("watched_movies")
    has_watched_cascade = any(
        fk.get("options", {}).get("ondelete") == "CASCADE" for fk in watched_fks
    )
    if not has_watched_cascade:
        for fk in watched_fks:
            op.drop_constraint(fk["name"], "watched_movies", type_="foreignkey")
        op.create_foreign_key(
            "watched_user_id_fkey_cascade",
            "watched_movies",
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        op.create_foreign_key(
            "watched_movie_id_fkey_cascade",
            "watched_movies",
            "movies",
            ["movie_id"],
            ["id"],
            ondelete="CASCADE",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "watched_movies", type_="foreignkey")
    op.drop_constraint(None, "watched_movies", type_="foreignkey")
    op.create_foreign_key(
        op.f("watched_movies_user_id_fkey"),
        "watched_movies",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("watched_movies_movie_id_fkey"),
        "watched_movies",
        "movies",
        ["movie_id"],
        ["id"],
    )
    op.drop_constraint("uq_user_watched_movie", "watched_movies", type_="unique")
    op.drop_constraint(None, "movies", type_="foreignkey")
    op.create_foreign_key(
        op.f("movies_user_id_fkey"), "movies", "users", ["user_id"], ["id"]
    )
    op.drop_constraint("uq_user_tmdb_movie", "movies", type_="unique")
    # ### end Alembic commands ###
